"use client";

import Link from "next/link";
import { useState } from "react";
import type { LucideIcon } from "lucide-react";
import {
  Activity, BarChart3, Bell, Bot, BriefcaseBusiness, CalendarDays, ChevronDown, CircleHelp,
  Clapperboard, Command, CreditCard, FileText, FolderOpen, Gauge, ImageIcon, Share2,
  LayoutDashboard, Mail, Menu, MessageCircle, Palette, PanelLeftClose, Plus, Search, Settings,
  Sparkles, Users, WandSparkles, Workflow, X, Zap
} from "lucide-react";
import { appNavigation, type NavigationIcon } from "@/config/navigation";
import { demoDashboardSummary } from "@/features/dashboard/data/demo-dashboard";
import { PRODUCT } from "@/config/product";
import { AssistantStudio } from "@/components/features/assistant-studio";
import { MagnificStudio } from "@/components/features/magnific-studio";
import { ImageStudio } from "@/components/features/image-studio";
import { ResourcesStudio } from "@/components/features/resources-studio";

const iconByName: Readonly<Record<NavigationIcon, LucideIcon>> = {
  dashboard: LayoutDashboard, assistant: Bot, creative: WandSparkles, image: ImageIcon,
  video: Clapperboard, magnific: Sparkles, resources: FolderOpen, planner: CalendarDays,
  social: Share2, whatsapp: MessageCircle, analytics: BarChart3, ads: Gauge, email: Mail,
  page: FileText, automation: Workflow, crm: BriefcaseBusiness, brand: Palette, team: Users,
  billing: CreditCard, settings: Settings,
};

const labels = Object.fromEntries(appNavigation.map(({ slug, label }) => [slug, label]));

export function MarketingApp({ section }: { section: string }) {
  const [menuOpen,setMenuOpen] = useState(false);
  const [collapsed,setCollapsed] = useState(false);
  const [createOpen,setCreateOpen] = useState(false);
  const current = labels[section] ?? "Dashboard";
  return <div className={`os-shell ${collapsed?"is-collapsed":""}`}>
    <aside className={`os-sidebar ${menuOpen?"mobile-open":""}`}>
      <div className="os-brand"><span className="brand-mark">M</span><div><strong>MONOVA</strong><small>MARKETING OS</small></div><button className="icon-button collapse-button" onClick={()=>setCollapsed(!collapsed)} aria-label="Contraer navegación"><PanelLeftClose size={18}/></button><button className="icon-button mobile-close" onClick={()=>setMenuOpen(false)} aria-label="Cerrar navegación"><X size={18}/></button></div>
      <button className="workspace-switch" disabled title="El selector multiworkspace requiere autenticación"><span>UC</span><div><strong>{PRODUCT.demoWorkspace}</strong><small>Workspace demo</small></div><ChevronDown size={15}/></button>
      <nav className="os-nav" aria-label="Navegación principal">{appNavigation.map(({ slug, label, icon, badge }) => { const Icon = iconByName[icon]; return <Link key={slug} onClick={()=>setMenuOpen(false)} href={`/app/${slug}`} className={section===slug?"active":""} title={label}><Icon size={18}/><span>{label}</span>{badge&&<b>{badge}</b>}</Link>; })}</nav>
      <div className="sidebar-user"><div className="usage"><span><small>Uso de IA</small><b>68%</b></span><i><em/></i></div><div className="user-row"><span>BR</span><div><strong>Brandon R.</strong><small>Owner · Plan Pro</small></div><button className="icon-button"><ChevronDown size={14}/></button></div></div>
    </aside>
    {menuOpen&&<button className="sidebar-scrim" onClick={()=>setMenuOpen(false)} aria-label="Cerrar menú"/>}
    <main className="os-main">
      <header className="os-header"><button className="icon-button mobile-menu" onClick={()=>setMenuOpen(true)} aria-label="Abrir menú"><Menu size={20}/></button><div className="global-search" title="La búsqueda global requiere datos persistidos"><Search size={17}/><input disabled aria-label="Buscar" placeholder="Búsqueda disponible al conectar Auth y datos"/><kbd><Command size={12}/> K</kbd></div><div className="header-actions"><button className="create-button" onClick={()=>setCreateOpen(!createOpen)}><Plus size={17}/> Crear</button><button className="icon-button" disabled title="Centro de ayuda próximamente" aria-label="Ayuda"><CircleHelp size={18}/></button><button className="icon-button" disabled title="Requiere autenticación y Realtime" aria-label="Notificaciones"><Bell size={18}/></button><span className="header-avatar">BR</span></div></header>
      {createOpen&&<div className="create-popover"><strong>Crear nuevo</strong><Link onClick={()=>setCreateOpen(false)} href="/app/image-studio"><Plus size={15}/>Imagen con IA</Link><Link onClick={()=>setCreateOpen(false)} href="/app/creative-studio"><Plus size={15}/>Pieza creativa</Link><Link onClick={()=>setCreateOpen(false)} href="/app/magnific"><Plus size={15}/>Mejorar imagen</Link><Link onClick={()=>setCreateOpen(false)} href="/app/assistant"><Plus size={15}/>Consultar a Monova AI</Link></div>}
      {section==="dashboard"?<Dashboard/>:<ModulePage section={section} title={current}/>}
    </main>
  </div>;
}

function Dashboard() {
  const { metrics: stats, assistantInsights, channelPerformance, calendarItems } = demoDashboardSummary;
  return <div className="os-content">
    <div className="page-heading"><div><span className="demo-badge">DATOS DEMO</span><h1>Buenos días, Brandon</h1><p>Aquí tienes el resumen de tu marketing hoy.</p></div><button className="date-filter" disabled title="Periodo fijo para los datos demo"><CalendarDays size={16}/> Últimos 30 días <ChevronDown size={15}/></button></div>
    <section className="stats-grid">{stats.map(({id,label,formattedValue,changePercent,trend},i)=><article className="stat-card" key={id}><div><span>{label}</span><Activity size={16}/></div><strong>{formattedValue}</strong><small className={trend}>+{changePercent}% <span>vs. periodo anterior</span></small><svg viewBox="0 0 140 30"><path d={`M0 ${24-i} C30 ${28-i}, 35 ${7+i}, 65 ${16-i/2} S100 ${5+i}, 140 ${9+i/2}`} fill="none" stroke={trend==="negative"?"#ef4444":"#ff6a00"} strokeWidth="2"/></svg></article>)}</section>
    <section className="dashboard-grid">
      <article className="panel quick-create"><div className="panel-head"><div><div><h2>¿Qué quieres crear hoy?</h2><p>Empieza con una idea. Monova le da contexto.</p></div></div><Link href="/app/creative-studio">Más opciones →</Link></div><div className="creation-types">{[["Imagen",ImageIcon,"/app/image-studio"],["Video",Clapperboard,"/app/video-studio"],["Reel",Share2,"/app/creative-studio"],["Historia",ImageIcon,"/app/creative-studio"],["Anuncio",Zap,"/app/creative-studio"],["Logo",Palette,"/app/creative-studio"]].map(([x,I,href])=><Link href={href as string} key={x as string}><I size={18}/><span>{x as string}</span><small>{x==="Imagen"?"Post, banner, etc.":x==="Video"?"Estado de integración":"Crear con IA"}</small></Link>)}</div></article>
      <article className="panel ai-insights"><div className="panel-head"><div><span className="panel-icon dark"><Bot size={17}/></span><div><h2>Monova AI</h2><p>{assistantInsights.length} recomendaciones para hoy</p></div></div><span className="demo-badge">DEMO</span></div>{assistantInsights.map((insight)=><div className="insight" key={insight.id}><span><Sparkles size={15}/></span><div><strong>{insight.title}</strong><p>{insight.description}</p><Link href={insight.actionHref}>{insight.actionLabel} →</Link></div></div>)}</article>
      <article className="panel performance"><div className="panel-head"><div><h2>Rendimiento general</h2><p>Alcance e interacciones</p></div><span className="demo-badge">30 DÍAS</span></div><div className="chart-summary"><strong>248.9K</strong><span>+18.4%</span></div><svg viewBox="0 0 700 190" aria-label="Rendimiento demo"><defs><linearGradient id="g" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#ff6a00" stopOpacity=".23"/><stop offset="1" stopColor="#ff6a00" stopOpacity="0"/></linearGradient></defs><path d="M0 150 C70 148 78 106 145 120 S230 50 300 82 S390 128 450 60 S570 95 700 20 L700 190 L0 190Z" fill="url(#g)"/><path d="M0 150 C70 148 78 106 145 120 S230 50 300 82 S390 128 450 60 S570 95 700 20" fill="none" stroke="#ff6a00" strokeWidth="4"/></svg></article>
      <article className="panel channels"><div className="panel-head"><div><h2>Canales</h2><p>Contribución al alcance</p></div><Link href="/app/analytics">Ver análisis</Link></div>{channelPerformance.map((channel)=><div className="channel" key={channel.id}><span>{channel.name}</span><i><em style={{width:`${channel.contributionPercent}%`,background:channel.color}}/></i><b>{channel.contributionPercent}%</b></div>)}</article>
      <article className="panel schedule"><div className="panel-head"><div><h2>Calendario de contenidos</h2><p>Semana del 20 al 26 de julio</p></div><Link href="/app/planner">Ver calendario</Link></div><div className="week-row">{["Lun 20","Mar 21","Mié 22","Jue 23","Vie 24","Sáb 25","Dom 26"].map((day,i)=>{const item=calendarItems[i]; return <div className={i===3?"today":""} key={day}><span>{day}</span>{item&&<><b className={`content-dot dot-${i}`}>{item.title}</b><DemoCreative variant={i}/></>}</div>})}</div><div className="calendar-legend"><span>● Programado</span><span>● Publicado</span><span>● Borrador</span></div></article>
    </section>
  </div>;
}

function ModulePage({ section,title }: { section:string; title:string }) {
  if (["assistant","creative-studio","image-studio","video-studio","magnific","resources","planner","social","analytics","meta-ads","brand-center","automations"].includes(section)) {
    return <ToolModule section={section} title={title}/>;
  }
  const special: Record<string,string> = { "assistant":"Chat, ideas, análisis, copywriter y estrategia con contexto de Brand Brain.", "creative-studio":"Crea una pieza de principio a fin: formato, canal, producto, estilo, modelo y aprobación.", "image-studio":"Generación y edición de imágenes mediante proveedores desacoplados.", "video-studio":"Jobs asíncronos con progreso, reintentos y registro de consumo.", "resources":"Biblioteca central de imágenes, videos, logos, plantillas y generaciones.", "planner":"Calendario compartido de campañas, contenidos, tareas y aprobaciones.", "analytics":"Métricas demostrativas por canal, campaña, producto y periodo.", "brand-center":"Identidad, tono, audiencias, productos y activos que alimentan Brand Brain." };
  const configured = ["assistant"].includes(section);
  return <div className="os-content module-page"><div className="page-heading"><div><span className="demo-badge">{configured?"ADAPTER DISPONIBLE":"MODO DEMO"}</span><h1>{title}</h1><p>{special[section]??`El módulo ${title} está preparado dentro de la navegación de Monova Marketing OS.`}</p></div><button className="create-button" disabled title="Requiere conectar el proveedor de este módulo"><Plus size={17}/> Requiere conexión</button></div><section className="module-hero"><div className="module-visual"><span><Sparkles size={24}/></span><div><small>{PRODUCT.demoWorkspace}</small><h2>{configured?"Listo para trabajar con contexto":"Interfaz preparada · Integración pendiente"}</h2><p>{configured?"El endpoint existente de OpenAI se conserva y migrará a la capa multiproveedor.":"No hay credenciales válidas para este proveedor. Ninguna conexión real se presenta como activa."}</p></div></div><div className="module-steps">{["Configurar workspace","Conectar proveedor","Importar datos","Activar flujo"].map((x,i)=><div key={x}><span className={i===0?"done":""}>{i===0?<CheckIcon/>:i+1}</span><div><strong>{x}</strong><small>{i===0?"Datos demo disponibles":"Configuración pendiente"}</small></div></div>)}</div></section><section className="module-cards">{["Actividad reciente","Estado del sistema","Siguiente recomendación"].map((x,i)=><article key={x}><span className="panel-icon">{i===0?<Activity size={18}/>:i===1?<Gauge size={18}/>:<Bot size={18}/>}</span><h3>{x}</h3><p>{i===0?"Aún no hay actividad real en este workspace.":i===1?"La interfaz está operativa; el backend de este módulo es una fase posterior.":"Completa la configuración del Brand Center antes de conectar canales."}</p><button disabled>Integración pendiente</button></article>)}</section></div>;
}

function CheckIcon(){ return <span aria-label="Completado">✓</span> }

function ToolModule({section,title}:{section:string;title:string}) {
  if(section==="assistant") return <div className="tool-layout"><ToolRail title={title} items={["Chat","Ideas","Análisis","Copywriter","Planificador"]}/><div className="tool-canvas"><AssistantStudio/></div></div>;
  if(section==="magnific") return <div className="tool-layout"><ToolRail title={title} items={["Mejorar","Escalar","Restaurar","Detalles","Historial"]}/><div className="tool-canvas"><MagnificStudio/></div></div>;
  if(section==="resources") return <div className="tool-layout"><ToolRail title={title} items={["Buscar","Descargas","Favoritos","Colecciones"]}/><div className="tool-canvas"><ResourcesStudio/></div></div>;
  if(section==="image-studio") return <div className="tool-layout"><ToolRail title={title} items={["Generar","Editor","Plantillas","Mis medios","Favoritos","Kit de marca"]}/><div className="tool-canvas"><ImageStudio/></div></div>;
  if(section==="creative-studio") return <div className="tool-layout"><ToolRail title={title} items={["Generar","Editor","Plantillas","Mis medios","Favoritos","Kit de marca"]}/><div className="tool-canvas"><ImageStudio creative/></div></div>;
  const product = <DemoCreative variant={2} large/>;
  if(section==="video-studio") return <div className="tool-layout"><ToolRail title={title} items={["Generar","Editor","Plantillas","Mis medios","Favoritos","Kit de marca"]}/><section className="tool-canvas generator-tool"><div className="tool-title"><div><h1>{title}</h1><p>El proveedor de video todavía no está configurado.</p></div><span className="pending-badge">NO CONECTADO</span></div><div className="generator-grid"><form><label>Describe el video<textarea defaultValue="Reel de 15 segundos mostrando la resistencia de nuestros soportes de caucho"/></label><button type="button" className="generate-main" disabled title="Requiere configurar un proveedor de video">Configurar proveedor de video</button></form><div className="generated-preview">{product}<span>Vista previa · Datos demo</span></div></div></section></div>;
  if(section==="planner") return <div className="tool-layout"><ToolRail title="Planner" items={["Calendario","Lista","Campañas","Eventos"]}/><section className="tool-canvas"><div className="tool-title"><div><h1>Julio 2026</h1><p>Contenido, campañas y entregas del equipo.</p></div><button className="create-button" disabled title="Requiere autenticación y persistencia">Requiere Auth</button></div><CalendarMonth/></section></div>;
  if(section==="social") return <div className="tool-layout"><ToolRail title={title} items={["Publicaciones","Calendario","Bandeja","Comentarios","Menciones","Hashtags"]}/><section className="tool-canvas"><div className="tool-title"><div><h1>Redes sociales</h1><p>Publicaciones demo de Universal de Cauchos.</p></div><button className="create-button" disabled title="Requiere conectar Meta u otra red social">Conectar canal</button></div><div className="social-grid">{["Instagram","Instagram","Facebook","Instagram","Instagram"].map((x,i)=><article key={i}><small>{x}</small><b>{["Post Instagram","Reel Instagram","Post Facebook","Story Instagram","Post Instagram"][i]}</b>{product}<span className={i%2?"published":"scheduled"}>{i%2?"Publicado":"Programado"}</span></article>)}</div></section></div>;
  if(section==="analytics") return <div className="tool-layout"><ToolRail title={title} items={["Resumen","Audiencia","Contenido","Conversiones","Informes"]}/><section className="tool-canvas"><div className="tool-title"><div><h1>Resumen general</h1><p>Rendimiento demostrado del 1 al 31 de julio.</p></div><span className="demo-badge">DATOS DEMO</span></div><div className="mini-metrics">{[["Alcance","125.8K"],["Interacciones","8.47K"],["Clics","2.34K"],["Conversiones","356"],["Ventas","$12,450"]].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>↑ 18.6%</span></div>)}</div><div className="analytics-chart"><svg viewBox="0 0 900 300"><path d="M0 230 C90 205 140 220 215 180 S330 210 410 135 S560 185 650 95 S770 130 900 54" fill="none" stroke="#ff6a00" strokeWidth="4"/><path d="M0 250 C100 240 160 200 240 215 S400 155 510 175 S680 95 900 120" fill="none" stroke="#587cff" strokeWidth="3"/><path d="M0 265 C160 250 230 270 360 220 S540 240 690 185 S820 170 900 150" fill="none" stroke="#43c486" strokeWidth="3"/></svg></div></section></div>;
  if(section==="meta-ads") return <div className="tool-layout"><ToolRail title={title} items={["Campañas","Conjuntos","Anuncios","Reportes","Audiencias"]}/><section className="tool-canvas"><div className="tool-title"><div><h1>Campañas</h1><p>Vista de demostración; Meta Marketing API no está conectada.</p></div><span className="pending-badge">NO CONECTADO</span></div><DataTable/></section></div>;
  if(section==="brand-center") return <div className="tool-layout"><ToolRail title={title} items={["Identidad","Colores","Tipografías","Logos","Imágenes","Documentos"]}/><section className="tool-canvas"><div className="tool-title"><div><h1>Identidad de marca</h1><p>La fuente principal de contexto para Brand Brain.</p></div><button className="create-button" disabled title="Requiere autenticación y Storage">Requiere Storage</button></div><div className="brand-board"><div className="brand-logo-demo"><span>UC</span><div><b>UNIVERSAL</b><small>DE CAUCHOS</small></div></div><section><small>Colores de marca</small><div className="swatches">{["#ff6a00","#171719","#414149","#e5e5e8","#ffffff"].map(x=><i key={x} style={{background:x}} title={x}/>)}</div></section><section><small>Tipografía principal</small><strong className="type-sample">Inter <em>Aa</em></strong></section></div></section></div>;
  return <div className="tool-layout"><ToolRail title={title} items={["Flujos","Plantillas","Historial","Webhooks","Integraciones"]}/><section className="tool-canvas"><div className="tool-title"><div><h1>Automatizaciones</h1><p>Flujo demo · Nuevo cliente potencial.</p></div><span className="demo-badge">ACTIVO EN DEMO</span></div><div className="flow-canvas"><div>Nuevo lead<small>WhatsApp / Formulario</small></div><span>↓</span><div>Enviar mensaje<small>Bienvenida personalizada</small></div><span>↓</span><div>Etiquetar lead<small>Interés: soportes</small></div><span>↓</span><div>Notificar ventas<small>Asignar responsable</small></div></div></section></div>;
}

function ToolRail({title,items}:{title:string;items:string[]}){return <aside className="tool-rail"><h2>{title}</h2>{items.map((x,i)=><button className={i===0?"active":""} disabled={i!==0} title={i===0?x:`${x}: próximamente`} key={x}>{i===0?<Sparkles size={14}/>:<Activity size={14}/>} {x}</button>)}</aside>}
function CalendarMonth(){return <div className="month-grid">{["Lun","Mar","Mié","Jue","Vie","Sáb","Dom"].map(x=><b key={x}>{x}</b>)}{Array.from({length:35},(_,i)=><div key={i}><span>{i<2?"":i-1}</span>{[5,8,10,14,17,23,27].includes(i)&&<em>{i%2?"Post Instagram":"Campaña UGC"}</em>}</div>)}</div>}
function DataTable(){return <div className="data-table"><div className="tr head"><span>Campaña</span><span>Estado</span><span>Presupuesto</span><span>Resultados</span><span>ROAS</span></div>{[["Todo terreno","Activa","$50,000","Ventas","6.8"],["Tráfico web","Activa","$30,000","Clics","3.2"],["Reconocimiento","Pausada","$20,000","Alcance","2.1"],["Retargeting","Activa","$40,000","Ventas","8.4"]].map(x=><div className="tr" key={x[0]}>{x.map((y,i)=><span className={i===1?(y==="Activa"?"positive":"neutral"):""} key={y}>{y}</span>)}</div>)}</div>}
function DemoCreative({variant=0,large=false}:{variant?:number;large?:boolean}){return <div className={`demo-creative creative-${variant%5} ${large?"large":""}`} role="img" aria-label="Vista previa visual neutra y reemplazable"><span/><i/><b>DEMO</b></div>}
